export enum jsonConstant {
  uri = 'https://itunes.apple.com/us/rss/newfreeapplications/limit=2/json',
  errorMessage = 'Error',
  name = "im:name",
  image = "im:image",
  artist = "im:artist",
  releaseDate = "im:releaseDate",
  textInputColor = '#182747',
  search = 'Search',
  all = "All",
  listBackgroundColor = 'white',
  searchInputBorderColor = '#000000',
  searchInputBackgroundColor = '#EEF2E6',
  categoryTextBorderColor = '#B1B2FF',
  categoryTextBackgroundColor = '#B1B2FF',
  filterItemBackgroundColor = '#D8D8D8',
  detailPage = 'Detail Page',
  price = "im:price",
  amount = '0.00',
  gridView = "Grid",
  listView = "List",
  pickerContainerColor = '#D2DAFF',
  COUNTER_CHANGE = 'COUNTER_CHANGE',
  Home = 'Home',
  detailPageHeaderColor = '#D2DAFF',
  id = "im:id"
}
